### ISSUE TITLE
Failed to create instance of plugin

### ISSUE THREAD

**Issue by jeppevinkel** [galaxy119/OhNeinSix#1]
I am using ServerMod 3.3.0-A and am unable to use this plugin.

I get this error whenever I try to run the server with this plugin installed.
```[ERROR] [PLUGIN_LOADER] Failed to create instance of plugin OhNeinSix.OhNeinSix[/home/scp/scp_server/SCPSL_Data/../sm_plugins/OhNeinSix.dll]```

**Comment by galaxy119** [comment]
Because you're using Smod 3.3.0, update to 3.4.0
